
version: '3'
services:
    redis:
        image: redis:alpine
        expose:
            - 6379
        ports:
            - 6379:6379
        networks:
            - ratelimit-network
    ratelimit:
        image: envoyproxy/ratelimit:master
        command: /bin/ratelimit
        ports:
        - 8080:8080
        - 8081:8081
        - 6070:6070
        depends_on:
        - redis
        # - statsd
        networks:
        - ratelimit-network
        volumes:
        - $PWD/examples/ratelimit/config:/data/ratelimit/config
        environment:
        - USE_STATSD=false
        # - STATSD_HOST=statsd
        # - STATSD_PORT=9125
        - LOG_LEVEL=debug
        - REDIS_SOCKET_TYPE=tcp
        - REDIS_URL=redis:6379
        - RUNTIME_ROOT=/data
        - RUNTIME_SUBDIRECTORY=ratelimit
        - RUNTIME_WATCH_ROOT=false
networks:
  ratelimit-network: